version: 2.1

jobs:
    deploy:
        docker:
            - image: circleci/node:latest
        steps:
            - checkout
            - run: sudo npm i gulp-cli ts-node -g
            - run: npm i @massfice/sw-fairy-common-deploy-scripts typescript --save
            - run: gulp deploy --token $NPM_TOKEN

workflows:
    version: 2
    deploy:
        jobs:
            - deploy:
                  context:
                      - Shinobi War Fairy
                  filters:
                      branches:
                          only:
                              - main
